config/routes.rb
Rails.application.routes.draw do
  get 'pets/new'
  get 'sessions/new' 
  get 'pages/index'
  get 'pages/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index' #トップページ
  
  get 'users/index'
  resources :users
  
  get 'pets/index'
  resources :pets
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
  
  
  get 'comments/new'
  resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :pet
  
  validates :content, presence: true #presenceで空白禁止
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :pet
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :user_id, presence: true
  validates :type, presence: true
  self.inheritance_column = :_type_disabled#typeでエラーがでないよう
  
  validates :image, presence: true
  validates :prefecture, presence: true
  validates :city, presence: true
  validates :description, presence: true
  
  belongs_to :user
  has_many :favorites 
  has_many :favorited_users, through: :favorites, source: :user#誰にいいねされたか
 
  has_many :comments, dependent: :destroy#petが削除された際にcommentも
  
  mount_uploader :image, ImageUploader
  
  def self.search(search) #self.はpetを意味する
     if search
       where(['type LIKE ?', "%#{search}%"]) #検索とtypeの部分一致を表示。
     else
       all #全て表示させる
    end
 end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true #presenceで空白禁止
  
  validates :name, presence: true, length: { maximum: 15}
  
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])[a-z\d]{8,32}+\z/ #数字アルファベット混合で８〜３２文字
  validates :password, presence: true, length: { minimum: 8, maximum: 32}, format: { with: VALID_PASSWORD_REGEX}
  
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/ #@と.必須
  validates :email, presence: true, uniqueness: true, format: {with: VALID_EMAIL_REGEX} # uniquenessで重複禁止
  
  has_secure_password #password_confirmation（パスワード確認用の再入力）が使える
  
  has_many :pets, dependent: :destroy#user消えたら投稿も
  has_many :favorites, dependent: :destroy
  has_many :favorite_pets, through: :favorites, source: 'pet' #userが紐づいているfavoriteが紐づいているpetを取得
  

  def already_favorited?(pet)
    self.favorites.exists?(pet_id: pet.id)
  end


  #def favorited_by?(pet_id)
    #favorites.where(pet_id: pet_id).exists?
  #end
  
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  add_flash_types :success, :info, :warning, :danger
  
  helper_method :current_user, :logged_in? #ApplicationHelperでも使える
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
  
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  
  def new
    @comment = Comment.new
  end
  
  def create
    @comment = current_user.comments.new(comment_params)
    #@comment.user_id = current_user.id
    #@comment.pet_id = params[:pet_id]
    
    if @comment.save
      redirect_to pets_path, success: 'コメントしました'
    else
      flash.now[:danger] = "コメントできませんでした"
      render :new
    end
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to pets_path, success: '削除しました'
    
  end
  
  private
  def comment_params
    params.require(:comment).permit(:content, :pet_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite_pets = current_user.favorite_pets.order(created_at: :desc)
  end
  
  def create
    favorite = Favorite.new #インスタンス生成
    favorite.user_id = current_user.id #ログインユーザー保存
    favorite.pet_id = params[:pet_id] #index.htmlのfavorites_path(pet_id: pet.id)が入る
    
    if favorite.save
      redirect_to pets_path, success: 'ほしいしました'
    else
      redirect_to pets_path, danger: 'ほしいできませんでした'
    end
  end
  
  def destroy
    @favorite = Favorite.find_by(user_id: current_user.id, pet_id: params[:pet_id])
    @favorite.destroy
    redirect_to pets_path, success: 'ほしいから削除しました'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def about
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  
  def index
    @pets = Pet.all.order(created_at: :desc).search(params[:search])
    #Pet.all.新しいものから表示される.検索機能
  end
  
  def new
    @pet = Pet.new
  end
  
  def create
    @pet = current_user.pets.new(pet_params)

    if @pet.save
      redirect_to pets_path, success: '投稿しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end
  
  def edit
    @pet = Pet.find(params[:id])#データベースから対象のpet_idをとる
  end
  
  def update
    @pet = Pet.find(params[:id])#空のモデルを用意だと新規作成になり修正ではない
    @pet.update(params.require(:pet).permit(:image, :description, :type, :prefecture, :city))
    
    if @pet.save
    redirect_to pets_path, success: '編集しました'
    else
      flash.now[:danger] = "項目をすべて埋めてください"
      render :edit
    end
  end
  
  def destroy
     @pet = Pet.find(params[:id])
    if @pet.user_id == current_user.id
       @pet.destroy
       redirect_to pets_path, success: '削除しました'
    end
    
  end
  
  private
  def pet_params
    params.require(:pet).permit(:image, :description, :type, :prefecture, :city)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: session_params[:email])
    if user && user.authenticate(session_params[:password])
      log_in user
      redirect_to pets_path, success: 'ログインしました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end
    
  private
  def log_in(user)
      session[:user_id] = user.id #sessionで暗号化して保存
  end
  
  def log_out
    session.delete(:user_id) #sessionにあるuser_id削除
    @current_user = nil #ユーザー情報削除
  end
  
  def session_params
    params.require(:session).permit(:email, :password)#sessionのemailとパスワードのみ受け取る
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def show
  @user = current_user
  @pets = Pet.where(user_id: current_user.id).order(created_at: :desc)#自分の投稿したもの
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, success: "登録しました"
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new #newアクションを写す
    end
  end
  
  def edit
    @user = current_user
  end
  
  def update
    @user = User.find(params[:id])#空のモデルを用意だと新規作成になり修正ではない
    @user.update(params.require(:user).permit(:name, :email, :password, :password_confirmation))
    
    if @user.save
      redirect_to user_path(current_user.id), success: '編集しました'
    else
      flash.now[:danger] = "編集に失敗しました"
      render :edit
    end
  end
  
  def destroy 
    @user = User.find_by(id: params[:id])
    @user.destroy
    redirect_to("/")#トップへ
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)#userのnameとemailとパスワードのみ受け取る
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class="pet-index-wrapper">
  
  <div class="comment-container">
    <h1 class="text-center text">コメント</h1>
       
      <%= form_for @comment do |f|  %>
        <div class="row">
          <div class="col-md-4 col-md-offset-4">
            <%= f.text_area :content, class: "form-control", :size=>"50x8" %><!--formのサイズ変更-->
            <%= f.hidden_field :pet_id,value: params[:pet_id] %>
          </div>
        </div>
            
        <div class="row">
          <div class="btn-zone">
            <div class="col-md-offset-4 col-md-2">
              <%= button_tag :type => "submit", class: 'btn btn-primary rounded-pill btn-block' do %>
                <i class="fas fa-paw"> コメントする</i>
              <% end %>
            </div>
            <div class="col-md-2">
              <%= link_to pets_path, class: 'btn btn-primary rounded-pill btn-block' do %>
                <i class="fas fa-paw"> もどる</i>
              <% end %>
            </div>
          </div>
        </div>
       　
      <% end %>
      
  </div>
</div>

app/views/favorites/index.html.erb
<div class="pet-index-wrapper">
  <h1 class="text-center text">あなたがほしいした子</h1>
    <h4 class="text-center text">投稿主からの連絡をお待ちください。</h4>
      <div class="pet-container2">
        <div class="row row-eq-height">
          <% @favorite_pets.each do |pet| %>
            <div class="col-md-4 col-sm-6">
              <div class="card">
                <h4 class="card-header"><%= pet.type %></h4>
                  <div class="card-body">
                    <h5 class="pet-author">
                      <p class="pet-text">ユーザー名：<%= pet.user.try(:name) %></p>
                    </h5>
                    <p class="pet-text1">
                      <%= pet.prefecture %>
                    </p>
                    <p class="pet-text2">
                      <%= pet.city %>
                    </p>
                     <%= image_tag pet.image.url, style: 'height: 300px; width: 100%; object-fit: contain' %>
                    <div class="card-body">
                      <p class="message">
                        ＜メッセージ＞<br><%= pet.description %>
                      </p>
                      <p class="pet-text">
                        <%= pet.gender %>
                      </p>
       
                      <% if current_user.favorites.find_by(pet_id: pet.id) %>
                        <%= link_to favorites_path(pet_id: pet.id), method: :delete, data: { confirm: '解除しますか？'}, class: 'btn btn-success rounded-pill' do %>
                          <i class="fas fa-paw"> ほしい解除</i>
                        <% end %>
                      <% else %>
                        <%= link_to favorites_path(pet_id: pet.id), method: :post, class: 'btn btn-primary rounded-pill' do %>
                          <i class="fas fa-paw"> ほしい</i>
                        <% end %>
                      <% end %>
            
                      <%= link_to comments_new_path(pet_id: pet.id), class: 'btn btn-primary rounded-pill' do %>
                        <i class="far fa-comment-dots"> コメント</i>
                      <% end %>
                    
                      <ul id="faq-list", style="padding-inline-start: 0;">
                        <li class="faq-list-item">
                          <h5>コメント一覧</h5>
                          <span>+</span>
                            <div class="answer">
                              <% pet.comments.each do |comment| %>
                                <p class="pet-comment">
                                  <%= comment.user.name %>　
                                    <%= comment.content %>
                                    <% if logged_in? && current_user.id == pet.user_id %>
                                      <span class="delete"><%= link_to "削除", "/comments/#{comment.id}", method: :delete, data: { confirm: '削除しますか？'} %></span>
                                    <% end %>
                                </p>
                              <% end %>
                            </div>
                        </li>
                      </ul>
                        
                      <p class="time text-right"><%= pet.created_at.to_s(:datetime) %></p><!--.to_s(:datetime)でinitializers/time_format.rbを適用-->
                    </div>
                  </div>
              </div>
          　</div>
          <% end %>
        </div>
      </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jimopet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/a60a9ff68e.js" crossorigin="anonymous"></script>
   
  </head>

  <body>
    <% flash.each do |key, value| %> <!--登録フィードバック-->
  　　<div class="alert alert-<%= key %>" role="alert"><%= value %></div>
　　<% end %>
　　
　　<!-- ナビゲーションバー-->
　　<nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container", style="padding: 0;">
        <%= link_to "jimopet",root_path, class: "navbar-brand nav-text3"  %>
          
        <div class="menu-pc">
        <ul class="nav navbar-right nav-pills"> <!--nav-pillsで横並び-->
          <% if logged_in? %>
            <li>
              <%= link_to "マイページ", user_path(current_user.id), class: "nav-text" %>
            </li>
            <li>
              <%= link_to "ほしいリスト", favorites_index_path, class: "nav-text" %>
            </li>
            <li>
              <%= link_to "ペット投稿", pets_new_path, class: "nav-text" %>
            </li>
            <li>
              <%= link_to "ペット一覧", pets_path, class: "nav-text" %>
            </li>
            <li>
              <%= link_to "jimopetについて", pages_about_path, class: "nav-text" %>
            </li>
            <li>
              <%= link_to "ログアウト", logout_path, method: :delete, class: "nav-text" %>
            </li>
          <% else %>
            <li>
              <%= link_to "ペット一覧", pets_path, class: "nav-text2" %>
            </li>
            <li>
              <%= link_to "jimopetについて", pages_about_path, class: "nav-text2" %>
            </li>
            <li>
              <%= link_to "ログイン", login_path, class: "nav-text2" %>
            </li>
          <% end %>
        </ul>
        </div>
        
        <!--smf-->
        <div class="menu-smf">
          <input id="input" type="checkbox"> 
      <label id="label1" for="input"><div class="line1"></div><div class="line2"></div><div class="line3"></div></label> 
    <div id="content">
        <ul id="link", style="list-style: none; padding-left: 10px"> 
          <% if logged_in? %>
            <li style="padding: 40px 15px 15px 15px;">
              <%= link_to "マイページ", user_path(current_user.id), class: "nav-text", style: "font-size: 17px" %>
            </li>
            <li style="padding: 15px;">
              <%= link_to "ほしいリスト", favorites_index_path, class: "nav-text", style: "font-size: 17px" %>
            </li>
            <li style="padding: 15px;">
              <%= link_to "ペット投稿", pets_new_path, class: "nav-text", style: "font-size: 17px" %>
            </li>
            <li style="padding: 15px;">
              <%= link_to "ペット一覧", pets_path, class: "nav-text", style: "font-size: 17px" %>
            </li>
            <li style="padding: 15px;">
              <%= link_to "jimopetについて", pages_about_path, class: "nav-text", style: "font-size: 17px" %>
            </li>
            <li style="padding: 15px;">
              <%= link_to "ログアウト", logout_path, method: :delete, class: "nav-text", style: "font-size: 17px" %>
            </li>
          <% else %>
            <li style="padding: 40px 15px 15px 15px;">
              <%= link_to "ペット一覧", pets_path, class: "nav-text", style: "font-size: 17px" %>
            </li>
            <li style="padding: 15px;">
              <%= link_to "jimopetについて", pages_about_path, class: "nav-text2", style: "font-size: 17px" %>
            </li>
            <li style="padding: 15px;">
              <%= link_to "ログイン", login_path, class: "nav-text2", style: "font-size: 17px" %>
            </li>
          <% end %>
        </ul>
        </div>
        </div>
        
        
      </div>
    </nav>
    <%= yield %>
    <!--3秒で消える-->
    <script> 
  　$(function(){
    　$(".alert").fadeOut(4000);
      //コメント一覧
      $('.faq-list-item').click(function() {
        var $answer = $(this).find('.answer');
        
        if($answer.hasClass('open')) { 
          $answer.removeClass('open');
          $answer.slideUp();// slideUpメソッドを用いて、$answerを隠す

          $(this).find('span').text('+');
        } else {
          $answer.addClass('open'); 
          // slideDownメソッドを用いて、$answerを表示
          $answer.slideDown();
        
          $(this).find('span').text('-');
        }
      });
      
      $('#fade').hide().delay(300).fadeIn(3000);//0.3秒後に3秒かけてフェードイン
 　　 });
　　</script>
　　
  </body>
</html>

app/views/pages/about.html.erb
<div class="about-wrapper text-left">
  <div class="container top-about-container">
    <div class="jumbotron" style="left: 7vw; right: 7vw;" id="fade">
      <h1 class="display-4">jimopet</h1>
        <p class="lead">地元でペットを譲りたい人と飼いたい人とをつなげるサービスです。<br>犬、猫、鳥、魚など需要と供給さえマッチすればなんでもOK!
        <br>ペットに赤ちゃんができたから譲ろうという方！そして新しくペットが欲しい方！<br>
        <span style="font-family: 'Corben', cursive;">jimopet</span>を使いませんか？</p>
        <hr class="my-4">
          <p style="padding-bottom: 0; margin-bottom: 0;">ペットショップでは可愛い子がたくさん揃っており、彼らはたくさんの生活の豊かさや癒しを与えてくれます。しかし、その裏には売れ残った子たちへの殺処分、飼い主の勝手な都合により飼育放棄される子など残酷な現実も少なくありません。動物を「商品」ではなく「命」として扱っていただく為にも、
          <span style="font-family: 'Corben', cursive;">jimopet</span>では譲渡は全て地元で無料にて行います。一般家庭から飼育放棄されたり、ペットショップで殺されるペットが少しでもなくなるよう、このサイトを活用していただけると幸いです。</p><br>
          <% if logged_in? %>
            <div class="row">
              <div class="col-md-3 col-md-offset-3">
                <%= link_to pets_path, class: 'btn btn-primary rounded-pill btn-block' do %><!--btn-blockで横幅いっぱい-->
                  <i class="fas fa-paw"> ペット一覧</i>
                <% end %>
              </div>
              <div class="col-md-3">
                <%= link_to pets_new_path, class: 'btn btn-primary rounded-pill btn-block' do %>
                  <i class="fas fa-paw"> ペット投稿</i>
                <% end %>
              </div>
            </div>
          <% else%>
            <div class="row">
              <div class="col-md-3 col-md-offset-3">
                <%= link_to new_user_path, class: 'btn btn-primary rounded-pill btn-block' do %>
                  <i class="fas fa-paw"> 登　　録</i>
                <% end %>
              </div>
              <div class="col-md-3">
                <%= link_to login_path, class: 'btn btn-primary rounded-pill btn-block' do %>
                  <i class="fas fa-paw"> ログイン</i>
                <% end %>
              </div>
            </div>
          <% end %>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    
    <h1 class="text-white">jimopet</h1>
    <h4 class="text-white">〜地元でペットの譲渡をしませんか？〜</h4>
     <p class="text-white">ペットに赤ちゃんができて誰かに譲りたい！</br>ペットがほしい！</br>そんな双方の希望を叶えるマッチングサイトです！！</p>
　   <div class="row">
      <div class="col-md-offset-4 col-md-2">
        <%= link_to new_user_path, class: 'btn btn-primary rounded-pill btn-block purupuru' do %>
        <i class="fas fa-paw"> 登　　録</i>
        <% end %>
      </div>
      <div class="col-md-2">
        <%= link_to login_path, class: 'btn btn-primary rounded-pill btn-block purupuru' do %>
        <i class="fas fa-paw"> ログイン</i>
        <% end %>
      </div>
    </div>
    
  </div>
</div>

app/views/pets/edit.html.erb
<div class="pet-index-wrapper" >
  <div class="pet-new-container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center text">編集してください</h1>
        <%= render "form" %><!--_form.html.erbに書いてるやつ-->
      </div>
    </div>
  </div>
</div>

app/views/pets/indexold.html.erb
<div class="pet-index-wrapper">
  <h1 class="text-center text">飼い主探してます</h1>
    <h4 class="text-center text">引き取りたい子の「ほしいボタン」を押してください</h4>
      <div class="pet-container2">
        
        <div class="row">
        <% @pets.each do |pet| %>
      　　<div class="col-md-6">
          　<div class="card2">
              <h4 class="card-header"><%= pet.type %></h4>
              <div class="card-body">
              <h5 class="pet-author">
                <p class="pet-text">ユーザー名：<%= pet.user.name %></p>
              </h5>
              <p class="pet-text1">
                <%= pet.prefecture %>
              </p>
              <p class="pet-text2">
                <%= pet.city %>
              </p>
              <%= image_tag pet.image.url, style: 'max-height: 300px; width: 100%; object-fit: contain' %>
             
              
              <p class="message">
                ＜メッセージ＞<br>
                <%= pet.description %>
              </p>
              <p class="pet-text">
                <%= pet.gender %>
              </p>
              
                  <%= link_to favorites_path(pet_id: pet.id), method: :post, class: 'btn btn-primary rounded-pill' do %>
                    <i class="fas fa-paw"> ほしい</i>
                  <% end %>
                
                  <%= link_to comments_new_path(pet_id: pet.id), class: 'btn btn-primary rounded-pill' do %>
                    <i class="far fa-comment-dots"> コメント</i>
                  <% end %>
                  
                
              
            
            <h5>--コメント一覧--</h5>
            <% pet.comments.each do |comment| %>
            
                <p class="pet-text">
                  <%= comment.user.name %><br>
                  <%= comment.content %>
                  <% if logged_in? && current_user.id == comment.user_id %>
                <span class="delete"><%= link_to "削除", "/comments/#{comment.id}", method: :delete %></span><!--#{comment.id}で対象コメント-->
                <% end %>
                </p>
                
                
            <% end %>
            
            <% if logged_in? && current_user.id == pet.user_id %><!--ログインして尚且つ投稿主だけ見える-->
                <div class="edit text-right">
                  <%= link_to "編集", "/pets/#{pet.id}/edit" %>|
                  <%= link_to "削除", "/pets/#{pet.id}", method: :delete %>
                </div>
                <% end %>
            <p class="time text-right"><%= pet.created_at.to_s(:datetime) %></p><!--.to_s(:datetime)でinitializers/time_format.rbを適用-->
            </div>
            
          </div>
          
        </div>
      
      <% end %>
    </div>
  </div>
  <!--</div>-->
</div>

app/views/pets/new.html.erb
<div class="pet-index-wrapper" >
  <div class="pet-new-container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center text">譲る子の情報を入れてください</h1>
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="pet-index-wrapper">
  <div class="pet-container2">
  <div class="row", style="padding-top: 10px;">
    <div class="col-sm-4 col-sm-offset-4", style="padding-top: 10px;">
      <h2 class="text-center text", style="margin-top: 100px;">アカウント情報</h2>
  <table class="table", style="margin-top: 20px; background-color: #fff">
  <thead class="thead", style="font-family: 'Kosugi Maru', sans-serif;">
    <tr>
      <th scope="col">名前</th>
      <th scope="col">メールアドレス</th>
      <th scope="col">  </th>
      <th scope="col">  </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @user.name %></td>
      <td><%= @user.email %></td>
      <td style="padding-right: 0;"><%= link_to '編集', edit_user_path(current_user), class: 'btn btn2 btn-primary btn-xs' %></td>
      <td style="padding-right: 0; margin: 10px 0;"><%= link_to '削除', user_path(current_user), method: :delete, data: { confirm: '削除しますか？' }, class: 'btn btn2 btn-danger btn-xs' %></td>
    </tr>
     </tbody>
</table>
</div>
</div>
  <h1 class="text-center text", style="padding-top: 20px;">あなたが投稿したペット</h1>
    <h4 class="text-center mypage-text">※ほしいボタンが押されるとその方のアドレスが表示されます。<br>確認の上、ご連絡をお願いします。</h4>
      
        <div class="row row-eq-height">
          <% @pets.each do |pet| %>
            <div class="col-md-4 col-sm-6">
              <div class="card">
                <h4 class="card-header"><%= pet.type %></h4>
                  <div class="card-body">
                    <h5 class="pet-author">
                      <p class="pet-text">ユーザー名：<%= pet.user.name %></p>
                    </h5>
                      <p class="pet-text1">
                        <%= pet.prefecture %>
                      </p>
                      <p class="pet-text2">
                        <%= pet.city %>
                      </p>
                        <%= image_tag pet.image.url, style: 'height: 300px; width: 100%; object-fit: contain' %>
                      <div class="card-body">
                        <p class="message">
                          ＜メッセージ＞<br>
                          <%= pet.description %>
                        </p>
                        <p class="pet-text">
                          <%= pet.gender %>
                        </p>
                        <%= link_to comments_new_path(pet_id: pet.id), class: 'btn btn-primary rounded-pill' do %>
                          <i class="far fa-comment-dots"> コメント</i>
                        <% end %>
                        
                        <ul id="faq-list", style="padding-inline-start: 0;">
                          <li class="faq-list-item">
                            <h5>コメント一覧</h5>
                            <span>+</span>
                              <div class="answer">
                                <% pet.comments.each do |comment| %>
                                  <p class="pet-comment">
                                    <%= comment.user.name %>
                                    <%= comment.content %>
                                      <% if logged_in? && current_user.id == comment.user_id %>
                                        <span class="delete"><%= link_to "削除", "/comments/#{comment.id}", method: :delete, data: { confirm: '削除しますか？'} %></span><!--#{comment.id}で対象コメント-->
                                      <% end %>
                                  </p>
                                <% end %>
                              </div>
                          </li>
                        </ul>
                   
                        <% if logged_in? && current_user.id == pet.user_id %><!--ログインして尚且つ投稿主だけ見える-->
                          <div class="edit text-right">
                            <%= link_to "編集", "/pets/#{pet.id}/edit" %>|
                            <%= link_to "削除", "/pets/#{pet.id}", method: :delete, data: { confirm: '削除しますか？'} %>
                          </div>
                        <% end %>
                        
                        <p class="time text-right"><%= pet.created_at.to_s(:datetime) %></p><!--.to_s(:datetime)でinitializers/time_format.rbを適用-->
                      </div>
                  </div>
                    
                  <% if pet.favorited_users.count > 0 %><!--いいねした人が０より多い時-->
                    <div class="card-footer text-center">
                      <% pet.favorited_users.each do |user| %>
                        <p style="margin-bottom: 0; color: red;" class="purupuru">
                          ※ほしいボタンが押されています</p><p>
                          <span style="color: #337AB7;"><%= user.name %></span> さんが譲受希望です。<br>
                          <span style="color: #337AB7;"><%= user.email %></span> までご連絡をお願いします。
                        </p>
                      <% end %>
                    </div>
                  <% else %>
                    <div class="card-footer text-center">
                      <p style="margin-bottom: 0;">※まだほしいボタンは押されていません。</p>
                    </div>
                  <% end %>
                    
              </div>
        　　</div>
          <% end %>
        </div>
      </div>
</div>